
CREATE TABLE TEST_LOGGER (
	ID VARCHAR2(50) NOT NULL,
	NAME VARCHAR2(30) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	SORT_INDEX INTEGER DEFAULT 1 NOT NULL,
	CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	DATA_STATE INTEGER DEFAULT 0 NOT NULL,
	CONSTRAINT TEST_LOGGER_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE TEST_LOGGER IS '日志测试表';
COMMENT ON COLUMN TEST_LOGGER.ID IS '主键';
COMMENT ON COLUMN TEST_LOGGER.NAME IS '名称';
COMMENT ON COLUMN TEST_LOGGER.CONTENT IS '内容';
COMMENT ON COLUMN TEST_LOGGER.SORT_INDEX IS '排序号';
COMMENT ON COLUMN TEST_LOGGER.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TEST_LOGGER.DATA_STATE IS '数据状态:0为正常|其他为删除';
