DROP TABLE "TEST_SETTING";
DROP TABLE "TEST_LOGGER";
DROP TABLE "TEST_ROLE_CORE_INFO";
DROP TABLE "TEST_USER_CORE_INFO";
DROP TABLE "TEST_USER_ROLE_REF";
DROP TABLE "TEST_DEPARTMENT_CORE_INFO";

CREATE TABLE TEST_SETTING (
	ID VARCHAR(50) NOT NULL, 
	NAME VARCHAR(30) NOT NULL, 
	VALUE VARCHAR(50) NOT NULL, 
	VERSION INTEGER(8) DEFAULT 1 NOT NULL, 
	REMARK VARCHAR(200), 
	STATE TINYINT(3) NOT NULL, 
	CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATE_TIME TIMESTAMP, 
	DATA_STATE INTEGER(10) DEFAULT 1 NOT NULL, 
	CONSTRAINT TEST_SETTING_PK PRIMARY KEY (ID), 
	CONSTRAINT TEST_SETTING_NAME UNIQUE (NAME,DATA_STATE)
);


CREATE TABLE TEST_LOGGER (
	ID VARCHAR(50) NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	CONTENT VARCHAR(4000) NOT NULL,
	SORT_INDEX INTEGER(8) DEFAULT 1 NOT NULL,
	CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	DATA_STATE INTEGER(10) DEFAULT 1 NOT NULL,
	CONSTRAINT TEST_LOGGER_PK PRIMARY KEY (ID)
);


CREATE TABLE "TEST_ROLE_CORE_INFO" (
   "ID"                 VARCHAR(50)         NOT NULL,
   "TENANT_CODE"        VARCHAR(50)         DEFAULT '0' NOT NULL,
   "USER_TYPE"          TINYINT(3)           DEFAULT 1 NOT NULL,
   "ROLE_NAME"          VARCHAR(50)         NOT NULL,
   "ROLE_DESC"          VARCHAR(200),
   "SORT_INDEX"         INTEGER(8),
   "CREATOR_ID"         VARCHAR(50),
   "CREATE_TIME"        TIMESTAMP            DEFAULT CURRENT_TIMESTAMP NOT NULL,
   "DEFAULTS"           INTEGER(1)           DEFAULT 0 NOT NULL,
   "OPTIONS"            TEXT,
   "DATA_STATE"         INTEGER(10)          DEFAULT 1 NOT NULL,
   CONSTRAINT TEST_ROLE_CORE_PK PRIMARY KEY ("ID"),
   CONSTRAINT TEST_ROLE_CORE_NAME UNIQUE ("TENANT_CODE", "ROLE_NAME", "DATA_STATE")
);


CREATE TABLE "TEST_USER_CORE_INFO" (
   "ID"                 VARCHAR(50)         NOT NULL,
   "TENANT_CODE"        VARCHAR(50)         DEFAULT '0' NOT NULL,
   "USER_TYPE"          INTEGER(3)          DEFAULT 1 NOT NULL,
   "DEPT_CODE"          VARCHAR(50)         DEFAULT '0' NOT NULL,
   "USER_CODE"          VARCHAR(50),
   "USER_NAME"          VARCHAR(50),
   "NICK_NAME"          VARCHAR(50),
   "REAL_NAME"          VARCHAR(20),
   "PHONE"              VARCHAR(20),
   "EMAIL"              VARCHAR(50),
   "GENDER"             TINYINT(3)             NOT NULL,
   "PHOTO"              VARCHAR(120),
   "CITY"               VARCHAR(50),
   "IDENTITY"           VARCHAR(20),
   "PASSWORD"           VARCHAR(120),
   "CREATE_TIME"        TIMESTAMP            DEFAULT CURRENT_TIMESTAMP NOT NULL,
   "SUPERMAN"           TINYINT(1)             DEFAULT 0 NOT NULL,
   "USER_STATE"         TINYINT(3)             DEFAULT 0 NOT NULL,
   "USER_SOURCE"        TINYINT(3)             DEFAULT 0 NOT NULL,
   "OPTIONS"            TEXT,
   "DATA_STATE"         INTEGER(10)           DEFAULT 1 NOT NULL,
   CONSTRAINT TEST_USER_CORE_PK PRIMARY KEY ("ID")
);


CREATE TABLE "TEST_USER_ROLE_REF" (
   "ID"                 VARCHAR(50)         NOT NULL,
   "USER_ID"            VARCHAR(50)         NOT NULL,
   "ROLE_ID"            VARCHAR(50)         NOT NULL,
   "DATA_STATE"         INTEGER(10)         DEFAULT 1 NOT NULL,
   CONSTRAINT TEST_USER_ROLE_PK PRIMARY KEY ("ID"),
   CONSTRAINT TEST_USER_ROLE_REF UNIQUE ("USER_ID", "ROLE_ID", "DATA_STATE")
);

CREATE INDEX "TEST_USER_ROLE_USER_ID" ON "TEST_USER_ROLE_REF" ( "USER_ID" );
CREATE INDEX "TEST_USER_ROLE_ROLE_ID" ON "TEST_USER_ROLE_REF" ( "ROLE_ID" );


CREATE TABLE "TEST_DEPARTMENT_CORE_INFO" (
   "ID"                 VARCHAR(50)            NOT NULL,
   "TENANT_CODE"        VARCHAR(50)            NOT NULL DEFAULT '0',
   "USER_TYPE"          TINYINT(3)              NOT NULL DEFAULT 1,
   "DEPT_CODE"          VARCHAR(50)            NOT NULL,
   "DEPT_NAME"          VARCHAR(50)            NOT NULL,
   "PARENT_CODE"        VARCHAR(50)            NOT NULL,
   "SORT_INDEX"         INTEGER(8),
   "CREATOR_ID"         VARCHAR(50),
   "CREATE_TIME"        TIMESTAMP              NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "DATA_STATE"         INTEGER(10)            NOT NULL DEFAULT 1,
   CONSTRAINT "TEST_DEPT_CORE_PK" PRIMARY KEY ("ID"),
   CONSTRAINT "TEST_DEPT_CORE_CODE" UNIQUE ("TENANT_CODE", "DEPT_CODE", "DATA_STATE"),
   CONSTRAINT "TEST_DEPT_CORE_NAME" UNIQUE ("TENANT_CODE", "PARENT_CODE", "DEPT_NAME", "DATA_STATE")
);
